settings:
  files:
    outputs:
      status: false
      name: outputs.log
    logs:
      status: false
      name: logs.log
    errors:
      status: false
      name: errors.log
  legacy:
    force: false
    interval: 0s
server:
  status: true
  open: false
  port: 5002
  host: localhost
schema:
- name: api-auth
  path: api/auth
  args:
  - --registry=consul
  commands:
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    - ../../utils
    scripts:
    - command: make doc
      type: after
      path: ../../
      output: true
- name: srv-auth
  path: srv/auth
  args:
  - --registry=consul
  commands:
    run:
      status: true
  watcher:
    extensions:
    - proto
    - go
    paths:
    - /
    - ../../utils
    scripts:
    - command: make proto SRV=auth
      type: before
      path: ../../
      output: true
    - command: make doc
      type: after
      path: ../../
      output: true
- name: api-user
  path: api/user
  args:
    - --registry=consul
  commands:
    run:
      status: true
  watcher:
    extensions:
      - go
    paths:
      - /
      - ../../utils
    scripts:
      - command: make doc
        type: after
        path: ../../
        output: true
- name: srv-user
  path: srv/user
  args:
  - --registry=consul
  commands:
    run:
      status: true
  watcher:
    extensions:
    - proto
    - go
    paths:
    - /
    - ../../utils
    scripts:
    - command: make proto SRV=user
      type: before
      path: ../../
      output: true
    - command: make doc
      type: after
      path: ../../
      output: true
- name: api-sellinfo
  path: api/sellinfo
  args:
    - --registry=consul
  commands:
    run:
      status: true
  watcher:
    extensions:
      - go
    paths:
      - /
      - ../../utils
    scripts:
      - command: make doc
        type: after
        path: ../../
        output: true
- name: srv-sellinfo
  path: srv/sellinfo
  args:
    - --registry=consul
  commands:
    run:
      status: true
  watcher:
    extensions:
      - proto
      - go
    paths:
      - /
      - ../../utils
    scripts:
    - command: make proto SRV=sellinfo
      type: before
      path: ../../
      output: true
    - command: make doc
      type: after
      path: ../../
      output: true
- name: api-file
  path: api/file
  args:
    - --registry=consul
  commands:
    run:
      status: true
  watcher:
    extensions:
      - go
    paths:
      - /
      - ../../utils
    scripts:
    - command: make doc
      type: after
      path: ../../
      output: true
- name: srv-file
  path: srv/file
  args:
  - --registry=consul
  commands:
    run:
      status: true
  watcher:
    extensions:
    - proto
    - go
    paths:
    - /
    - ../../utils
    scripts:
    - command: make proto SRV=file
      type: before
      path: ../../
      output: true
    - command: make doc
      type: after
      path: ../../
      output: true
- name: api-avatar
  path: api/avatar
  args:
    - --registry=consul
  commands:
    run:
      status: true
  watcher:
    extensions:
      - go
    paths:
      - /
      - ../../utils
    scripts:
    - command: make doc
      type: after
      path: ../../
      output: true
- name: srv-avatar
  path: srv/avatar
  args:
  - --registry=consul
  commands:
    run:
      status: true
  watcher:
    extensions:
    - proto
    - go
    paths:
    - /
    - ../../utils
    scripts:
    - command: make proto SRV=avatar
      type: before
      path: ../../
      output: true
    - command: make doc
      type: after
      path: ../../
      output: true
- name: api-content
  path: api/content
  args:
    - --registry=consul
  commands:
    run:
      status: true
  watcher:
    extensions:
      - go
    paths:
      - /
      - ../../utils
    scripts:
    - command: make doc
      type: after
      path: ../../
      output: true
- name: srv-content
  path: srv/content
  args:
  - --registry=consul
  commands:
    run:
      status: true
  watcher:
    extensions:
    - proto
    - go
    paths:
    - /
    - ../../utils
    scripts:
    - command: make proto SRV=content
      type: before
      path: ../../
      output: true
    - command: make doc
      type: after
      path: ../../
      output: true
- name: api-buyinfo
  path: api/buyinfo
  args:
    - --registry=consul
  commands:
    run:
      status: true
  watcher:
    extensions:
      - go
    paths:
      - /
      - ../../utils
    scripts:
      - command: make doc
        type: after
        path: ../../
        output: true
- name: srv-buyinfo
  path: srv/buyinfo
  args:
  - --registry=consul
  commands:
    run:
      status: true
  watcher:
    extensions:
    - proto
    - go
    paths:
    - /
    - ../../utils
    scripts:
    - command: make proto SRV=buyinfo
      type: before
      path: ../../
      output: true
    - command: make doc
      type: after
      path: ../../
      output: true
- name: api-message
  path: api/message
  args:
    - --registry=consul
  commands:
    run:
      status: true
  watcher:
    extensions:
      - go
    paths:
      - /
      - ../../utils
    scripts:
      - command: make doc
        type: after
        path: ../../
        output: true
- name: srv-message
  path: srv/message
  args:
  - --registry=consul
  commands:
    run:
      status: true
  watcher:
    extensions:
    - proto
    - go
    paths:
    - /
    - ../../utils
    scripts:
    - command: make proto SRV=message
      type: before
      path: ../../
      output: true
    - command: make doc
      type: after
      path: ../../
      output: true
- name: api-tag
  path: api/tag
  args:
    - --registry=consul
  commands:
    run:
      status: true
  watcher:
    extensions:
      - go
    paths:
      - /
      - ../../utils
    scripts:
      - command: make doc
        type: after
        path: ../../
        output: true